trivio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic.base import TemplateView
from django.conf.urls import url
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('trivioapp.urls')),
    #path('home', TemplateView.as_view(template_name='home.html'), name='home'),
    path('trivio/', include('django.contrib.auth.urls')),
]

trivioapp/urls.py
from django.urls import path
from django.conf.urls import url
from trivioapp import views
from django.views.generic.base import TemplateView
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('signup/', views.signup, name='signup'),
    #url(r'^question/(?P<pk>\d+)/$', views.question, name='question'),
    url(r'^leaderboard/(?P<pk>\d+)/$', views.leaderboard,name='leaderboard'),
    #path('test', TemplateView.as_view(template_name='question.html'), name='test'),
    #path('test',views.test,name='test'),
    path('home/', views.home,name='home'),
    path('', views.question,name=''),
    path('profile/',views.profile,name='profile'),
    path('contact-us/',views.contact,name='contact'),
    url(r'^account_activation_sent/$', views.account_activation_sent, name='account_activation_sent'),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',views.activate, name='activate'),
    path('activate/<uidb64>/<token>/', views.activate, name='activate'),
    path('test/',views.test,name='test'),
    path('test2/',views.test2,name='test2'),
    #url(r'^(?P<string>[ \w\-]+)/$',views.question, name=''),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

trivioapp/models.py
from django.db import models
import os
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.contrib.auth.models import AbstractUser
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver


def default_score():
    return 0

def default_interval():
    return 10
class CustomUser(AbstractUser):
    user_name = models.CharField(blank=False, max_length=255)
    name = models.CharField(blank=False, max_length=255)
    score=models.IntegerField(default=default_score())
    college=models.CharField(max_length=60,blank=False,null=False)
    status=models.IntegerField(default=0,blank=False)
    flag=models.IntegerField(default=0,blank=False)
    email_confirmed = models.BooleanField(default=False)
    def __str__(self):
        return self.name
    def publish(self):
        self.save()
@receiver(post_save, sender=AbstractUser)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        CustomUser.objects.create(CustomUser=instance)
    instance.CustomUser.save()

class Question(models.Model):
    question=models.CharField(max_length=300)
    answer=models.CharField(max_length=50,blank=False)
    option1=models.CharField(max_length=50,blank=False)
    option2=models.CharField(max_length=50,blank=False)
    option3=models.CharField(max_length=50,blank=False)
    option4=models.CharField(max_length=50,blank=False)
    def publish(self):
        self.save()

    def __str__(self):
        return self.question


class Event(models.Model):
    Event_name=models.CharField(default="trivio",max_length=50,blank=False)
    event_start=models.DateTimeField(auto_now_add=False)
    interval=models.IntegerField(default=default_interval())

trivioapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser,Question

class SignUpForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email','college','name',)

class CustomUserChangeForm(UserChangeForm):

    class Meta(UserChangeForm.Meta):
        model = CustomUser
        #fields = ('username', 'email','college','score','name',)
        fields = UserChangeForm.Meta.fields


class ReplyForm(forms.ModelForm):
	class Meta:
		model=Question
		fields=('answer',)

trivioapp/views.py
from .models import Question,CustomUser,Event
from django.contrib.auth.decorators import login_required
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render, get_object_or_404,render ,redirect
from .forms import SignUpForm,ReplyForm
from django.http import HttpResponse,JsonResponse
from django.contrib.auth.models import User
from django.contrib.auth import login

#from django.http import HttpResponseRedirect

from django.utils import timezone
import datetime
from django.utils.timezone import utc

# for email activation link
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .forms import SignUpForm
from .tokens import account_activation_token
from django.core.mail import send_mail
from django.utils.encoding import force_text
from trivio import settings as sett
from django.utils.http import urlsafe_base64_decode

# class SignUp(generic.CreateView):
#     form_class = SignUpForm
#     success_url = reverse_lazy('login')
#     template_name = 'signup.html'

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            e=request.POST.get('email')
            current_site = get_current_site(request)
            subject = 'Activate Your Trivio Account'
            message = render_to_string('account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            #user.email_user(subject, message)
            send_mail(subject,message,sett.EMAIL_HOST_USER, [e, ], fail_silently=False)
            return redirect('account_activation_sent')
        else:
            return HttpResponse("Time Expired, Try again")
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})

def activate(request, uidb64, token):
    uid = urlsafe_base64_decode(uidb64).decode()
    if len(uid)>len(CustomUser.objects.all()):
        return HttpResponse("Time Expired, Try again")
    user = CustomUser.objects.get(id=int(uid))

    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.email_confirmed = True
        user.save()
        return HttpResponse("Authentication success go to login")
        #login(request, user)
        return redirect('home')
        
    else:
        return HttpResponse(str(user)+str(account_activation_token.check_token(user, token)))
        return render(request, 'account_activation_invalid.html')

def account_activation_sent(request):
    if request.user.is_anonymous:
        return HttpResponse('Check your Email')


def question(request):
    if request.user.is_anonymous:
        return redirect('home')
    event=Event.objects.get(id=1)
    timenow=((datetime.datetime.now()).strftime('%Y:%m:%d:%H:%M:%S'))
    timenow=datetime.datetime.strptime(timenow,'%Y:%m:%d:%H:%M:%S')
    eventtime=(event.event_start) + datetime.timedelta(hours=5.5)
    eventtime=datetime.datetime.strptime((eventtime.strftime('%Y:%m:%d:%H:%M:%S')),'%Y:%m:%d:%H:%M:%S')
    quiztime=float((len(Question.objects.all())*(event.interval)))+5
    t=int(request.user.id)
    user=CustomUser.objects.get(id=t)
    if user.status<1:
        return redirect('home')
    if (user.status>len(Question.objects.all()) or timenow>(eventtime+ datetime.timedelta(seconds=quiztime))):
        #return HttpResponse(str(eventtime+ datetime.timedelta(seconds=quiztime)))
        user.status=0
        user.save()
        user.publish()
        return redirect('leaderboard')
        #return HttpResponse(str(timenow)+"----"+str(eventtime+datetime.timedelta(seconds=quiztime))+" ----"+str(user.status)+str(len(Question.objects.all())))
    if request.method == "POST":
        score=(request.user.score)
        question = get_object_or_404(Question, pk=str(user.status))
        user_answer=request.POST.get('answer')
        user.flag=0
        if(str(user_answer)==str(question.answer)):
            user.score+=1
            user.flag=1
        (user.status)+=1
        user.save()
        user.publish()
        return redirect('')
    else:
        form=ReplyForm()
        score=user.score
        if int(user.flag)==1:
            message="Correct! "
        else:
            message="Wrong :( "
        if user.status==1:
            message="Hello! welcome to Trivio"
        question = get_object_or_404(Question, pk=str(user.status))
        sec=(timenow-eventtime).total_seconds()
        timeleft=10000
        return render(request,'question.html',{'message':message,'question': question,'form':form,'timeleft':timeleft,'sec':sec,})


def home(request):
    timenow = datetime.datetime.now() #.strftime('%H:%M:%S') #.strftime('%d %b %Y %H:%M:%S')
    event=Event.objects.get(id=1)
    eventtime=(event.event_start) + datetime.timedelta(hours=5.5)
    eventtime=(eventtime.strftime('%Y:%m:%d:%H:%M:%S'))
    eventtime=datetime.datetime.strptime(eventtime,'%Y:%m:%d:%H:%M:%S')
    timenow=(timenow.strftime('%Y:%m:%d:%H:%M:%S'))
    timenow=datetime.datetime.strptime(timenow,'%Y:%m:%d:%H:%M:%S')
    timeleft=eventtime-timenow
    if timeleft >datetime.timedelta(seconds=5):
        timeleft=timeleft.total_seconds()
        return render(request, 'welcome.html', {'timeleft':timeleft},)
    elif (timeleft <datetime.timedelta(seconds=5) and timeleft >datetime.timedelta(seconds=-2)):
        t=int(request.user.id)
        user=CustomUser.objects.get(id=t)
        user.status=1
        user.save()
        user.publish()
        return redirect('')
    else:
        return HttpResponse("the event has already started try next game")



def leaderboard(request,pk):
    limit = CustomUser.objects.all().count()
    limit=int(limit/50)+1
    if int(pk)>=limit:
        return redirect('../0/')
    pos=(int(pk))*50
    p=int(pk)-1
    l=int(pk)+1
    if l==limit:
        l=-1
    if not request.user.is_anonymous:
        user = CustomUser.objects.filter(id=(request.user.id))
        rank = CustomUser.objects.filter(score__gte=request.user.score).count()
        participants = CustomUser.objects.filter().order_by('-score')[pos+1:pos+51]
        return render(request, 'leaderboard.html', {'participants': participants,'rank':rank,'user':user,'position':pos,'p':p,'l':l},)
    
    participants = CustomUser.objects.filter().order_by('-score')[pos+1:pos+11]
    
    return render(request, 'leaderboard.html', {'participants': participants,'position':pos,'p':p,'l':l},)



def profile(request):
    return render(request,'profile.html')

def contact(request):
    return render(request,'contact.html')

def test(request):
    participants = CustomUser.objects.filter().order_by('-score')
    return render(request, 'ques.html', {'participants': participants},)

def test2(request):
    form=ReplyForm()
    message="hello"
    question="Where are you?"
    return render(request,'question.html',{'message':message,'question': question,'form':form,})

trivioapp/templates/account_activation_email.html
{% autoescape off %}
Hi {{ user.username }},

Please click on the link below to confirm your registration:

http://{{ domain }}{% url 'activate' uidb64=uid token=token %}
{% endautoescape %}

trivioapp/templates/account_activation_invalid.html
<h1> Sorry, try again</h1>
<h2>Probably Time Expired</h2>

trivioapp/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Contact Us</title>
	<meta name="description" content=".">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald" />
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/contact.css" %}">
    <link rel="stylesheet" href="{% static "css/menu.css" %}">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="wrapper">

	<nav>
        <ul style="visibility: hidden;">
                <li><a href="#"></a></li>
                <li><a href="#"></a></li>
                <li><a href="#">
    
                </a></li>
        </ul>
		<div class="button">
			<a class="btn-open" href="#"></a>
		</div>
	</nav>

	<div class="overlay">
		<div class="wrap">
			<ul class="wrap-nav">
				<li><a href="#">About</a>
				</li>
				<li><a href="#">Services</a>
				</li>
				<li><a href="#">Work</a>
				</li>
			</ul>
			<div class="social">
				<a href="https://www.facebook.com/arhn.nitd/">
					<div class="social-icon">
						<i class="fa fa-facebook"></i>
					</div>
				</a>
				<a href="https://twitter.com/aarohan_nitdgp?lang=en">
					<div class="social-icon">
						<i class="fa fa-twitter"></i>
					</div>
				</a>
				<a href="https://www.youtube.com/user/arhnNITD">
					<div class="social-icon">
						<i class="fa fa-youtube"></i>
					</div>
				</a>
				<p>
					Made by WDCT<br>
				</p>
			</div>
		</div>
	</div>

	<div class="main-content p-3 mb-5" style="background: transparent; box-shadow: 0px 0px 0px rgba(0, 0, 0, 0);">
		<div class="row contacts_holder">
			<div class="col contact">
				<div class="card">
					<img src="https://www.w3schools.com/howto/img_avatar.png" alt="Avatar" style="width:100%">
					<div class="container">
						<h4><b>John Doe</b></h4> 
						<p>Member</p> 
					</div>
					<div class="container">
						📱  +91-1234567890
					</div>
					<div class="container">
						<i class="fa fa-envelope" aria-hidden="true"></i>
						<i class="fa fa-facebook" aria-hidden="true"></i>
						<i class="fa fa-twitter" aria-hidden="true"></i>
					</div>
				</div>
			</div>
			<div class="col contact">
				<div class="card">
					<img src="https://www.w3schools.com/howto/img_avatar2.png" alt="Avatar" style="width:100%">
					<div class="container">
						<h4><b>Jane Doe</b></h4> 
						<p>Member</p> 
					</div>
					<div class="container">
						📱  +91-1234567890
					</div>
					<div class="container">
						<i class="fa fa-envelope" aria-hidden="true"></i>
						<i class="fa fa-facebook" aria-hidden="true"></i>
						<i class="fa fa-twitter" aria-hidden="true"></i>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer class="footer">
		<div class="row footer-menu">
			<span class="col spcn">

			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
		</div>
	</footer>
	<div class="left-footer">
		Handcrafted with ❤ by WDCT<br>
	</div>
	<script src="{% static 'js/menu.js' %}"></script>
</body>
</html>

trivioapp/templates/leaderboard.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Leaderboard</title>
	<meta name="description" content=".">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald" />
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/menu.css" %}">
    <link rel="stylesheet" href="{% static "css/leaderboard.css" %}">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="wrapper">

	<div class="lead-content shadow-lg p-3 mb-5">

		<div class="row info-box">
			<div class="row">
				<div class="col top-icon">
					Trivio Icon
				</div>
			</div>
			<div class="row title-bar">
				<div class="col">
					Rank
				</div>
				<div class="col">
					Userame
				</div>
				<div class="col">
					College
				</div>
				<div class="col">
					Score
				</div>
			</div>
		</div>
		{% with pos=position %}
        {% for participant in participants %}
		<div class="row rankings-area">
			<div class="row ranking-item">
				<div class="col">
					{{forloop.counter|add:pos}}
				</div>
				<div class="col">
					{{ participant.username}}
				</div>
				<div class="col">
					{{participant.college}}
				</div>
				<div class="col">
					{{participant.score}}
				</div>
            </div>
        </div>
        <div class="row space-area">
		</div>
		{% endfor %}
		{% endwith %}

		<div class="row space-area">
		</div>
		<div class="row space-area">
		</div>
		<div class="row space-area">
		</div>
		{% if request.user.username %}
		<div class="row rankings-area">
			<div class="row ranking-item">
				<div class="col">
					{{rank}}
				</div>
				<div class="col">
					{{request.user.username}}
				</div>
				<div class="col">
					{{request.user.college}}
				</div>
				<div class="col">
					{{request.user.score}}
				</div>
            </div>
        </div>
        <div class="row space-area">
        </div>
		{% endif %}
		<div class="row space-area">
		</div>
		
			{% if p != -1 %}
				<a href="../{{p}}"><button style="left: 12vw;position: absolute;">Previous</button></a>
			{% endif %}
			{% if l != -1 %}
				<a href="../{{l}}"><button style="right: 12vw;position: absolute;">Next</button></a>
			{% endif %}
		<div class="row space-area" style="height:4vh;">
		</div>
    </div>

	<footer class="footer">
		<div class="row footer-menu">
			<span class="col spcn">

			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
		</div>

	</footer>
    <script src="{% static 'js/menu.js' %}"></script>

</body>
</html>

trivioapp/templates/profile.html
{% block title %}Profile{% endblock %}

{% block content %}
{% if user.is_authenticated %}
  Hi {{ user.username }}! 
  your score is :{{user.score}}
  <p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a> | <a href="{% url 'signup' %}">signup</a>
{% endif %}
{% endblock %}

trivioapp/templates/ques.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Leaderboard</title>
	<meta name="description" content=".">
	<meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Oswald" />
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
    {% load static %}
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/menu.css" %}">
    <link rel="stylesheet" href="{% static "css/leaderboard.css" %}">
	<link rel="stylesheet" type="text/css" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
</head>
<body class="wrapper">

	<div class="lead-content shadow-lg p-3 mb-5">

		<div class="row info-box">
			<div class="row">
				<div class="col top-icon">
					Trivio Icon
				</div>
			</div>
			<div class="row title-bar">
				<div class="col">
					Rank
				</div>
				<div class="col">
					Userame
				</div>
				<div class="col">
					College
				</div>
				<div class="col">
					Score
				</div>
			</div>
        </div>
        {% for participant in participants %}
		<div class="row rankings-area">
			<div class="row ranking-item">
				<div class="col">
					{{forloop.counter}}
				</div>
				<div class="col">
					{{ participant.username}}
				</div>
				<div class="col">
					{{participant.college}}
				</div>
				<div class="col">
					{{participant.score}}
				</div>
            </div>
        </div>
        <div class="row space-area">
        </div>
        {% endfor %}

    </div>


	<footer class="footer">
		<div class="row footer-menu">
			<span class="col spcn">

			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
			<span class="col opt">
				<p class="footer-opt">
					<a href="">Menu</a>
				</p>
			</span>
		</div>

	</footer>
    <!-- <script type="text/javascript" src="js/menu.js"></script> -->
    <script src="{% static 'js/menu.js' %}"></script>

</body>
</html>

trivioapp/templates/signup.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Trivio|SignUp</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head>
<body>
  <h2 style="text-align:center;">Sign up</h2>
  <form method="post" style="padding-bottom:2%;color: rgb(0, 0, 0);">{% csrf_token %}
      <p><label for="id_username">Username:</label> <input type="text" name="username" maxlength="150" autofocus="" required="" id="id_username"> <span class="helptext"></span></p><ul><li>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only ! ¯\_(ツ)_/¯</li></ul>
      <p><label for="id_name">Name:</label> <input type="text" name="name" maxlength="255" required="" id="id_name"></p>
      <p><label for="id_email">Email address:</label> <input type="email" name="email" maxlength="254" id="id_email"></p><span class="helptext"></span></p><ul><li>Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only ! ¯\_(ツ)_/¯</li></ul>
      <p><label for="id_college">College:</label> <input type="text" name="college" maxlength="60" required="" id="id_college"></p>
      <p><label for="id_password1">Password:</label> <input type="password" name="password1" required="" id="id_password1"> <span class="helptext"></span></p><ul><li>Your password can't be too similar to your other personal information.</li><li>Your password must contain at least 8 characters.</li><li>Your password can't be a commonly used password.</li><li>Your password can't be entirely numeric.</li></ul><p></p>
      <p><label for="id_password2">Password confirmation:</label> <input type="password" name="password2" required="" id="id_password2"> <span class="helptext"></span></p><ul><li>Enter the same password as before, for verification (^J^)</li></ul>
      <button type="submit">Sign up</button>
    </form>
  </body>
  </html>